### ISSUE TITLE
Incorrect splitting full name

### ISSUE THREAD

**Issue by TheHolyWaffle** [saadq/latexresu.me#19]
Under profile, enter the following full name: "Bert De Geyter" and select template 2.

Result: only "Geyter" is bold

Expected Result: "De Geyter" should be bold

**Comment by saadq** [comment]
Hmm, this had actually been intentional but I suppose it would make more sense to bold everything except the first name.

**Comment by aviral1701** [comment]
@saadq 
Hey!
 I would like to work on this issue and fix it. Should I do it?

**Comment by saadq** [comment]
Hey @aviral1701, I would be very happy to accept your contribution. The source code for generating each template is available [here](https://github.com/saadq/latexresu.me/tree/master/app/server/src/generator/templates). You'll want to look at the `generateProfileSection` function for each template. I believe only a few templates actually need to splite the name, so you'll only need to modify a couple I think. Let me know if you have any questions.

**Comment by aviral1701** [comment]
@saadq  Thanks man! I'm on it!

**Comment by saadq** [comment]
As a sidenote, I just pushed a small commit to fix some styling in the top bar, so just remember to `git pull` at some point to get the changes I just pushed :)

**Comment by TheHolyWaffle** [comment]
Maybe giving the user the option to enter his first and last name separately makes more sense instead of making a guess on how to split the full name.

**Comment by saadq** [comment]
I was originally going with that, but I thought it might be a bit confusing for people with middle names. They may think they would have to omit it. Unless I also added a middle name field, but I figured it would just be easier for the user to type it all in one place and easier for myself as well so I wouldn't have to add a bunch more if checks for each part of the name (since every field needs to be made optional).
