### ISSUE TITLE
Trouble with node and npm

### ISSUE THREAD

**Issue by aviral1701** [saadq/latexresu.me#29]
Hi 
As suggested by you I was trying to get node and npm working so that I can continue to contribute to your project.But I am facing errors and can't seem to find a way out.Can you help me out please?

node --version
v8.1.4
sudo npm --version
5.0.3
**Steps that I follow :**
1. clone the repo
2. go to the directory and run "npm install".
3.run "npm run lint"
**throws out this:**
> latexresu.me@0.1.0 lint /home/d3xt3r/Desktop/latexresu.me
> npm run lint:client && npm run lint:server

> latexresu.me@0.1.0 lint:client /home/d3xt3r/Desktop/latexresu.me
> cd app/client && npm run lint

> latexresume-client@0.1.0 lint /home/d3xt3r/Desktop/latexresu.me/app/client
> blyss | snazzy

sh: 1: blyss: not found
sh: 1: snazzy: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! latexresume-client@0.1.0 lint: `blyss | snazzy`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the latexresume-client@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/d3xt3r/.npm/_logs/2017-07-24T15_48_30_614Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! latexresu.me@0.1.0 lint:client: `cd app/client && npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the latexresu.me@0.1.0 lint:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/d3xt3r/.npm/_logs/2017-07-24T15_48_30_689Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! latexresu.me@0.1.0 lint: `npm run lint:client && npm run lint:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the latexresu.me@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

Any help would be appreciated.

**Comment by saadq** [comment]
Hey @aviral1701, glad to hear you're still interested in contributing! 

I may have incorrectly described the setup, so let me fix that. When you run `npm install`, it basically installs all the `dependencies` and `devDependencies` that are listed in the `package.json` file. The `package.json` file in the root directory of the project has no dependencies, but you can find the actual client dependencies in `app/client/package.json` and the server dependencies in `app/server/package.json`. The only reason I have a `package.json` in the root directory is so that I can run some scripts that will run both on client and on server.

If you want to install both the client and server dependencies, you can run `npm run build` from the root directory. You can see [here](https://github.com/saadq/latexresu.me/blob/master/package.json#L11) what this script does: it runs `npm run build:client && npm run build:server`. If you look a bit further down in the file, you can see that [`build:client`](https://github.com/saadq/latexresu.me/blob/master/package.json#L18) goes into the `client` directory and runs `npm install`. The `build:server` script does the same thing for the server.

If you check out the [`readme`](https://github.com/saadq/latexresu.me#developing), you can see the main scripts that you want to use from the root directory. You can also check out the [client readme](https://github.com/saadq/latexresu.me/tree/master/app/client) to see what scripts you can do from the `app/client` folder and the [app/server](https://github.com/saadq/latexresu.me/tree/master/app/server) readme to see what scripts you can run from the `app/server` folder.

I might have overcomplicated my explanation here, so let me know if I can clarify anything.

**Comment by aviral1701** [comment]
@saadq Got it working.Thanks for all the help and such elaborative explanation, really helpful!
I'm closing this issue.
