### ISSUE TITLE
Compiling source code locally

### ISSUE THREAD

**Issue by vignesh-sankaran** [saadq/latexresu.me#36]
Does anyone know what command I can use to compile the LaTeX source? I get an error stating that I have to use XeLaTeX or LuaTex :(

**Comment by saadq** [comment]
Ahh, sorry I definitely need to document this somewhere...

Most of the templates just use the normal `latex` command while a few use `xelatex` or `lualatex`. Right now, you can just look at [this file](https://github.com/saadq/latexresu.me/blob/master/app/server/src/generator/templates/index.js#L60) and look at the `cmd` property for each template to see which command you should run. If the template doesn't have a `cmd` property, that means it is just the normal `latex` command.

**Comment by saadq** [comment]
This should be fixed in the new version. When you download the LaTeX source, a `README.md` file will be included in the zip that will look something like this:

---

# Resumake Template 4
> LaTeX code generated at [resumake.io](https://resumake.io)

## Usage
To generate a PDF from this LaTeX code, navigate to this folder in a terminal and run:

    xelatex resume.tex

## Requirements
You will need to have `xelatex` installed on your machine.

Alternatively, you can use a site like [ShareLaTeX](https://sharelatex.com) to build and edit your LaTeX instead.

---
